name: kathy code
on: push
jobs:


  deploy:
    
    name: deploy prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - name: Install php-cs-fixer
      - run: |
          curl -L https://cs.symfony.com/download/php-cs-fixer-v2.phar -o php-cs-fixer
          sudo chmod a+x php-cs-fixer
          sudo mv php-cs-fixer /usr/local/bin/php-cs-fixer
      - name: Run php-cs-fixer
        run: php-cs-fixer fix --dry-run sr
